### ISSUE TITLE
Missing docker file

### ISSUE THREAD

**Issue by NorbertFenk** [Petras3/travis_oa#1]
Hello :)

Could you please dockerize your application? :) 

It is good for testing and for faster product delivery too.

Thank you! :)

**Comment by Petras3** [comment]
What should i build into the image?
Just the application or tests or both of them?

**Comment by Petras3** [comment]
> Hello :)
> 
> Could you please dockerize your application? :)
> 
> It is good for testing and for faster product delivery too.
> 
> Thank you! :)

What should i build into the image?
Just the application or tests or both of them?

**Comment by NorbertFenk** [comment]
I think the docker container should compile and run the application. :) You don't have to bake the code into the container image, it can be solved by mounting the source code as a volume.
